services:
  demo-app:
    image: davidjk522/centralserver:latest  # Use the pre-built image-> do not rebuild every time
    container_name: demo-app  # Simple container name
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Add this line